### ISSUE TITLE
Few more words on the docs

### ISSUE THREAD

**Issue by lmeysel** [PixlOne/logiops#10]
Heyhey,

first of all: Great job! Maybe you should use some tags like "Logitech Options for Linux" because that was what I tried to find. I more or less stumbled over this lib while trying to find out why libratbag does not work with my Master 2S anymore.

Although this package seems not to be finished by far, I am surprised how great it works even with gestures! But it took much more time than actually necessary to getting things to work for me (I would consider myself as a semi-experienced Linux user).

So...
* for the config-wiki, maybe you can tell users entering the `logid`-command will help to identify the device... i know it is obvious but it took some time for me to come across this idea.
* also in the config-wiki, there is a discrepancy between your gesture-config and the gestures in the example config. In the wiki you're telling sth like `buttons: ( { gesture object }, { gesture object } ... );`, whereas the gestures actually are wrapped within an action (as given in example-config)
* and then it might be worth to mention, that logiops expects the `logid.cfg` within the `/etc`-directory (I was changing the `logid.cfg` within the `logiops`-folder and then re`make install` :expressionless:)

But using this lib I finally can get all the loved features out of my Master 2S using Linux (that was one of the main problems why I still was using windows on my box...)

Again: Thanks for your great work!

**Comment by PixlOne** [comment]
Yeah, I really haven't spread the word about this project too much because I was still working on it and I also don't really know where to do it. If you can spread it around and/or possibly find some people to help, please feel free to do it.

I actually haven't thought of launching logid to show device names. Thanks, I'll put that in the wiki.

Yeah, that should say `gestures: ( { gesture object }, { gesture object } ... )`, I don't know how that happened.

Also, I forgot to update the Configuration part of the wiki after changing the default location to `/etc/logid.cfg`.

I'll fix these in a bit, thanks.
